Implemented API to crud user event
gajendraJangid421/Event-Management-Application pull request #11
Opened 2023-06-26 17:18 UTC by sagarzond

2023-06-27 09:53 UTC, sagarzond commented on event_management/src/main/java/com/example/event_management/controller/EventsController.java
> +    public Events UpdateById(@PathVariable String id, @Valid @RequestBody Events events){
```suggestion
    public Events updateById(@PathVariable String id, @Valid @RequestBody Events events){
```

2023-06-27 09:53 UTC, sagarzond commented on event_management/src/main/java/com/example/event_management/controller/UsersController.java
> +    public Users UpdateById(@PathVariable(value = "id") String userId, @Valid @RequestBody Users users){
```suggestion
    public Users updateById(@PathVariable(value = "id") String userId, @Valid @RequestBody Users users){
```

2023-06-27 09:53 UTC, sagarzond commented on event_management/src/main/java/com/example/event_management/model/Events.java
> +    @NotBlank(message = "Add Event name!")
```suggestion
    @NotBlank(message = "'name' should not be null or blank")
```

2023-06-27 09:53 UTC, sagarzond commented on event_management/src/main/java/com/example/event_management/model/Events.java
> +    private String date;
This field can store both date and time both.
```suggestion
    @Column(name = "date")
    @NotNull(message = "'dateTime' should not null")
    private LocalDateTime dateTime;
```

2023-06-27 09:53 UTC, sagarzond commented on event_management/src/main/java/com/example/event_management/model/Events.java
> +    private String time;
No need to have this field as per above comment

2023-06-27 09:53 UTC, sagarzond commented on event_management/src/main/java/com/example/event_management/model/Events.java
> +    @NotBlank(message = "Add Location!")
```suggestion
    @NotBlank(message = "'location' should not be null or blank")
```

2023-06-27 09:53 UTC, sagarzond commented on event_management/src/main/java/com/example/event_management/model/Events.java
> +    private int totalSeats;
not required as it is a primitive integer. By default, it will going to have 0 value.
```suggestion
    private int totalSeats;
```

2023-06-27 09:53 UTC, sagarzond commented on event_management/src/main/java/com/example/event_management/model/UserEvent.java
> +    @Column(name = "booked", columnDefinition = "BIT")
No need to use this as by default it stores true/false
```suggestion
    @Column(name = "booked")
```

2023-06-27 09:53 UTC, sagarzond commented on event_management/src/main/java/com/example/event_management/model/UserEvent.java
> +    private boolean bookmarked;
same as above comment
```suggestion
    @Column(name = "bookmarked")
    private boolean bookmarked;
```

2023-06-27 09:53 UTC, sagarzond commented on event_management/src/main/java/com/example/event_management/model/UserEvent.java
> +    @Column(name = "attended", columnDefinition = "BIT")
same as above comment
```suggestion
    @Column(name = "attended")
```

2023-06-27 09:53 UTC, sagarzond commented on event_management/src/main/java/com/example/event_management/model/Users.java
> +    @NotBlank(message = "Add unique Username!")
```suggestion
    @NotBlank(message = "'username' should not be null or blank")
```

2023-06-27 09:53 UTC, sagarzond commented on event_management/src/main/java/com/example/event_management/model/Users.java
> +    @NotBlank(message = "Add Name!")
```suggestion
    @NotBlank(message = "'fullName' should not be null or blank")
```

2023-06-27 09:53 UTC, sagarzond commented on event_management/src/main/java/com/example/event_management/model/Users.java
> +    @NotBlank(message = "Add Email!")
```suggestion
    @NotBlank(message = "'email' should not be null or blank")
```

2023-06-27 09:53 UTC, sagarzond commented on event_management/src/main/java/com/example/event_management/model/Users.java
> +    @NotBlank(message = "Add Mobile!")
```suggestion
    @NotBlank(message = "'mobileNumber' should not be null or blank")
```

2023-06-27 09:53 UTC, sagarzond commented on event_management/src/main/java/com/example/event_management/model/Users.java
> +    private String role;
Create enul for UserRole which will having following 2 values
- USER
- ADMIN
This will also impact on FE and existing records.

2023-06-27 10:11 UTC, sagarzond commented on event_management/src/main/java/com/example/event_management/service/EventsService.java
> +        event.setId(UUID.randomUUID().toString());
add validation here that totalSeats can not be zero

2023-06-27 10:11 UTC, sagarzond commented on event_management/src/main/java/com/example/event_management/service/EventsService.java
> +
Populate seatsLeft = totalSeats as FE will not going to send seatsLeft as it BE field only

2023-06-27 10:11 UTC, sagarzond commented on event_management/src/main/java/com/example/event_management/service/EventsService.java
> +        event.setTotalSeats(events.getTotalSeats());
Populate seatsLeft = totalSeats as FE will not going to send seatsLeft as it BE field only

2023-06-27 10:11 UTC, sagarzond commented on event_management/src/main/java/com/example/event_management/service/EventsService.java
> +        Events event = eventsRepository.findById(events.getId()).orElseThrow(() -> new UnAuthorisedException("Event not found"));
add validation here that totalSeats can not be zero

2023-06-27 10:11 UTC, sagarzond commented on event_management/src/main/java/com/example/event_management/service/LoginService.java
> +        }
why login request will send token as it don't have it.

2023-06-27 10:11 UTC, sagarzond commented on event_management/src/main/java/com/example/event_management/service/LoginService.java
> +        if (Objects.isNull(loginRequest.getUsername()) || Objects.isNull(loginRequest.getPassword())){
```suggestion
        if (StringUtils.isBlank(loginRequest.getUsername()) || StringUtils.isBlank(loginRequest.getPassword())){
```

2023-06-27 10:11 UTC, sagarzond commented on event_management/src/main/java/com/example/event_management/service/UserEventService.java
> +    public void deleteByEventId(String id) {
```suggestion
    public void deleteByEventId(String eventId) {
```

2023-06-27 10:11 UTC, sagarzond commented on event_management/src/main/java/com/example/event_management/service/UserEventService.java
> +        }
```suggestion
       userEventRepository.deleteByEventId(eventId);
```

2023-06-27 10:11 UTC, sagarzond commented on event_management/src/main/java/com/example/event_management/service/UserEventService.java
> +        }
```suggestion
       userEventRepository.deleteByUserId();
```

2023-06-27 10:11 UTC, sagarzond commented on event_management/src/main/java/com/example/event_management/service/UserEventService.java
> +            }
Take booked status in request
```suggestion
            bookEvent.setBooked(userEvent.getBooked())
```

2023-06-27 10:11 UTC, sagarzond commented on event_management/src/main/java/com/example/event_management/service/UserEventService.java
> +                    .booked(true)
```suggestion
                    .booked(userEvent.getBooked())
```

2023-06-27 10:11 UTC, sagarzond commented on event_management/src/main/java/com/example/event_management/service/UserEventService.java
> +        }
same like above comment valid here

2023-06-27 10:11 UTC, sagarzond commented on event_management/src/main/java/com/example/event_management/service/UserEventService.java
> +        }
same like above comment valid here

2023-06-27 10:11 UTC, sagarzond commented on event_management/src/main/java/com/example/event_management/service/UsersService.java
> +            throw new DuplicateUsernameException("Existing Username");
```suggestion
            throw new DuplicateUsernameException("'userName' is not available. It is already used by another user");
```

2023-06-27 10:20 UTC, gajendraJangid421 commented on event_management/src/main/java/com/example/event_management/controller/EventsController.java
> +    public Events UpdateById(@PathVariable String id, @Valid @RequestBody Events events){
updated

2023-06-27 10:21 UTC, gajendraJangid421 commented on event_management/src/main/java/com/example/event_management/controller/UsersController.java
> +    public Users UpdateById(@PathVariable(value = "id") String userId, @Valid @RequestBody Users users){
updated

2023-06-27 10:21 UTC, AtulxD123 requested changes

2023-06-27 10:21 UTC, AtulxD123 commented on event_management/.gitignore
> +build/
add .idea, we dont need that directory on github

2023-06-27 10:21 UTC, AtulxD123 commented on event_management/src/main/java/com/example/event_management/controller/EventsController.java
> +    public Events findById(@PathVariable String id){
the method name should be getById instead of findById

2023-06-27 10:21 UTC, AtulxD123 commented on event_management/src/main/java/com/example/event_management/controller/EventsController.java
> +        eventsService.delete(id);
service method name should be deleteById

2023-06-27 10:21 UTC, AtulxD123 commented on event_management/src/main/java/com/example/event_management/controller/LoginController.java
> +@RequestMapping(path = "/api/users")
path should be /api/login,
why are we using users here?

2023-06-27 10:21 UTC, AtulxD123 commented on event_management/src/main/java/com/example/event_management/controller/UsersController.java
> +    public Users findById(@PathVariable String id) {
getById

2023-06-27 10:21 UTC, AtulxD123 commented on event_management/src/main/java/com/example/event_management/service/UserEventService.java
> +        List<UserEvent> userEventList = userEventRepository.findAll();
why do we need to get all the event and then delete?

we can directly delete by id.
Please refractor

2023-06-27 10:21 UTC, AtulxD123 commented on event_management/src/main/java/com/example/event_management/service/UserEventService.java
> +        List<UserEvent> userEventList = userEventRepository.findAll();
same here

2023-06-27 10:21 UTC, AtulxD123 commented on event_management/src/main/java/com/example/event_management/service/UsersService.java
> +        isPasswordCorrect = forgetPassword.getNewPassword().equals(forgetPassword.getConfirmPassword());
This validation should be part of frontend,

2023-06-27 10:23 UTC, gajendraJangid421 commented on event_management/src/main/java/com/example/event_management/model/Events.java
> +    @NotBlank(message = "Add Event name!")
updated

2023-06-27 10:30 UTC, gajendraJangid421 commented on event_management/src/main/java/com/example/event_management/model/Events.java
> +    @NotBlank(message = "Add Location!")
updated

2023-06-27 10:31 UTC, gajendraJangid421 commented on event_management/src/main/java/com/example/event_management/model/Events.java
> +    private int totalSeats;
updated

2023-06-27 10:46 UTC, gajendraJangid421 commented on event_management/src/main/java/com/example/event_management/model/UserEvent.java
> +    @Column(name = "booked", columnDefinition = "BIT")
updated

2023-06-27 10:46 UTC, gajendraJangid421 commented on event_management/src/main/java/com/example/event_management/model/UserEvent.java
> +    private boolean bookmarked;
updated

2023-06-27 10:47 UTC, gajendraJangid421 commented on event_management/src/main/java/com/example/event_management/model/UserEvent.java
> +    @Column(name = "attended", columnDefinition = "BIT")
updated

2023-06-27 10:49 UTC, gajendraJangid421 commented on event_management/src/main/java/com/example/event_management/model/Users.java
> +    @NotBlank(message = "Add unique Username!")
updated

2023-06-27 10:49 UTC, gajendraJangid421 commented on event_management/src/main/java/com/example/event_management/model/Users.java
> +    @NotBlank(message = "Add Name!")
updated

2023-06-27 10:50 UTC, gajendraJangid421 commented on event_management/src/main/java/com/example/event_management/model/Users.java
> +    @NotBlank(message = "Add Email!")
updated

2023-06-27 10:50 UTC, gajendraJangid421 commented on event_management/src/main/java/com/example/event_management/model/Users.java
> +    @NotBlank(message = "Add Mobile!")
updated

2023-06-27 19:37 UTC, gajendraJangid421 commented on event_management/src/main/java/com/example/event_management/model/Events.java
> +    private String date;
updated to LocalDate as it is kept separate in Frontend

2023-06-27 19:38 UTC, gajendraJangid421 commented on event_management/src/main/java/com/example/event_management/model/Events.java
> +    private String time;
updated to LocalTime as it is kept separate in Frontend

2023-06-28 08:45 UTC, gajendraJangid421 commented on event_management/src/main/java/com/example/event_management/service/EventsService.java
> +        event.setId(UUID.randomUUID().toString());
updated

2023-06-28 08:46 UTC, gajendraJangid421 commented on event_management/src/main/java/com/example/event_management/service/EventsService.java
> +
updated

2023-06-28 09:11 UTC, gajendraJangid421 commented on event_management/src/main/java/com/example/event_management/service/EventsService.java
> +        event.setTotalSeats(events.getTotalSeats());
updated

2023-06-28 09:17 UTC, gajendraJangid421 commented on event_management/src/main/java/com/example/event_management/service/EventsService.java
> +        Events event = eventsRepository.findById(events.getId()).orElseThrow(() -> new UnAuthorisedException("Event not found"));
updated

2023-06-28 09:24 UTC, gajendraJangid421 commented on event_management/src/main/java/com/example/event_management/service/LoginService.java
> +        if (Objects.isNull(loginRequest.getUsername()) || Objects.isNull(loginRequest.getPassword())){
updated

2023-06-28 09:28 UTC, gajendraJangid421 commented on event_management/src/main/java/com/example/event_management/service/UserEventService.java
> +    public void deleteByEventId(String id) {
updated

2023-06-28 09:35 UTC, gajendraJangid421 commented on event_management/src/main/java/com/example/event_management/service/UserEventService.java
> +                    .booked(true)
updated to userEvent.isBooked()

2023-06-28 09:36 UTC, gajendraJangid421 commented on event_management/src/main/java/com/example/event_management/service/UserEventService.java
> +        }
updated

2023-06-28 09:36 UTC, gajendraJangid421 commented on event_management/src/main/java/com/example/event_management/service/UserEventService.java
> +        }
updated

2023-06-28 09:44 UTC, gajendraJangid421 commented on event_management/src/main/java/com/example/event_management/service/UsersService.java
> +            throw new DuplicateUsernameException("Existing Username");
updated

2023-06-28 09:45 UTC, gajendraJangid421 commented on event_management/.gitignore
> +build/
updated

2023-06-28 09:48 UTC, gajendraJangid421 commented on event_management/src/main/java/com/example/event_management/controller/EventsController.java
> +    public Events findById(@PathVariable String id){
updated

2023-06-28 09:50 UTC, gajendraJangid421 commented on event_management/src/main/java/com/example/event_management/controller/EventsController.java
> +        eventsService.delete(id);
updated

2023-06-28 09:54 UTC, gajendraJangid421 commented on event_management/src/main/java/com/example/event_management/controller/LoginController.java
> +@RequestMapping(path = "/api/users")
updated

2023-06-28 09:55 UTC, gajendraJangid421 commented on event_management/src/main/java/com/example/event_management/controller/UsersController.java
> +    public Users findById(@PathVariable String id) {
updated

2023-06-28 15:58 UTC, gajendraJangid421 commented on event_management/src/main/java/com/example/event_management/service/UserEventService.java
> +        }
updated using Query and Modifying annotations

2023-06-28 16:01 UTC, gajendraJangid421 commented on event_management/src/main/java/com/example/event_management/service/UserEventService.java
> +        }
updated using Query and Modifying annotations

2023-06-28 16:06 UTC, gajendraJangid421 commented on event_management/src/main/java/com/example/event_management/service/UserEventService.java
> +        List<UserEvent> userEventList = userEventRepository.findAll();
updated using Query and Modifying annotations

2023-06-28 16:06 UTC, gajendraJangid421 commented on event_management/src/main/java/com/example/event_management/service/UserEventService.java
> +        List<UserEvent> userEventList = userEventRepository.findAll();
updated using Query and Modifying annotations

2023-06-28 19:09 UTC, gajendraJangid421 commented on event_management/src/main/java/com/example/event_management/service/UserEventService.java
> +        }
updated and added increment and decrement of seatsLeft after booking

2023-06-28 19:09 UTC, gajendraJangid421 commented on event_management/src/main/java/com/example/event_management/service/UserEventService.java
> +        }
updated

2023-06-28 19:10 UTC, gajendraJangid421 commented on event_management/src/main/java/com/example/event_management/service/UserEventService.java
> +                    .booked(true)
updated and added increment and decrement of seatsLeft after booking

2023-06-28 19:10 UTC, gajendraJangid421 commented on event_management/src/main/java/com/example/event_management/service/UserEventService.java
> +            }
updated and added increment and decrement of seatsLeft after booking

2023-06-28 19:11 UTC, gajendraJangid421 commented on event_management/src/main/java/com/example/event_management/service/LoginService.java
> +        }
updated

2023-06-30 08:16 UTC, gajendraJangid421 commented on event_management/src/main/java/com/example/event_management/model/Users.java
> +    private String role;
updated

2023-06-30 09:26 UTC, sagarzond commented on event_management/src/main/java/com/example/event_management/exception/ObjectValidationException.java
> +public class ObjectValidationException extends RuntimeException{
```suggestion
public class ValidationException extends RuntimeException{
```

2023-06-30 09:26 UTC, sagarzond commented on event_management/src/main/java/com/example/event_management/model/Events.java
> +    @Min(0)
This is not part of the request body. So no need to add this validation.

2023-06-30 09:26 UTC, sagarzond commented on event_management/src/main/java/com/example/event_management/model/Users.java
> +    private RoleStatus roleStatus;
```suggestion
    private Role role;
```

2023-06-30 09:26 UTC, sagarzond commented on event_management/src/main/java/com/example/event_management/repository/UserEventRepository.java
> +    @Query("delete UserEvent userEvent where userEvent.eventId = :eventId")
```suggestion
    @Query("DELETY UserEvent userEvent WHERE userEvent.eventId = :eventId")
```

2023-06-30 09:26 UTC, sagarzond commented on event_management/src/main/java/com/example/event_management/repository/UserEventRepository.java
> +    @Query("delete UserEvent userEvent where userEvent.userId = :userId")
```suggestion
    @Query("DELETE UserEvent userEvent WHERE userEvent.userId = :userId")
```

2023-06-30 09:26 UTC, sagarzond commented on event_management/src/main/java/com/example/event_management/service/EventsService.java
> +        if(event.getTotalSeats()<1){
```suggestion
        if(event.getTotalSeats() < 1){
```

2023-06-30 09:26 UTC, sagarzond commented on event_management/src/main/java/com/example/event_management/service/EventsService.java
> +        if(events.getTotalSeats()<1){
```suggestion
        if(events.getTotalSeats() < 1){
```

2023-06-30 09:26 UTC, sagarzond commented on event_management/src/main/java/com/example/event_management/service/SessionService.java
> +        sessionRepository.deleteById(sessionRepository.findByToken(token).getId());
```suggestion
        sessionRepository.deleteByToken(token);
```

2023-06-30 09:26 UTC, sagarzond commented on event_management/src/main/java/com/example/event_management/service/UserEventService.java
> +    @Test
why test is required here?

2023-06-30 09:26 UTC, sagarzond commented on event_management/src/main/java/com/example/event_management/service/UserEventService.java
> +    @Test
why test is required here?

2023-06-30 09:26 UTC, sagarzond commented on event_management/src/main/java/com/example/event_management/service/UserEventService.java
> +        }
Check this only if user is trying book seat
```suggestion
        if(event.getSeatsLeft() == 0 && bookEvent.isBooked()) {
            throw new ObjectValidationException("No seat is available. Event is full");
        }
```

2023-06-30 09:26 UTC, sagarzond commented on event_management/src/main/java/com/example/event_management/service/UserEventService.java
> +                event.setSeatsLeft(event.getSeatsLeft()+1);
```suggestion
                event.setSeatsLeft(event.getSeatsLeft() + 1);
```

2023-06-30 09:26 UTC, sagarzond commented on event_management/src/main/java/com/example/event_management/service/UserEventService.java
> +                event.setSeatsLeft(event.getSeatsLeft()-1);
```suggestion
                event.setSeatsLeft(event.getSeatsLeft() - 1);
```

2023-06-30 09:26 UTC, sagarzond commented on event_management/src/main/java/com/example/event_management/service/UserEventService.java
> +            bookEvent.setBooked(!bookEvent.isBooked());
why change in value?
```suggestion
            bookEvent.setBooked(bookEvent.isBooked());
```

2023-06-30 09:26 UTC, sagarzond commented on event_management/src/main/java/com/example/event_management/controller/LoginController.java
> +    public void logOut(@PathVariable String id){
For this API, no need to pass anything. You can take token from AUTHORIZATION header

2023-06-30 09:39 UTC, gajendraJangid421 commented on event_management/src/main/java/com/example/event_management/exception/ObjectValidationException.java
> +public class ObjectValidationException extends RuntimeException{
updated

2023-06-30 09:41 UTC, gajendraJangid421 commented on event_management/src/main/java/com/example/event_management/model/Events.java
> +    @Min(0)
updated

2023-06-30 09:42 UTC, gajendraJangid421 commented on event_management/src/main/java/com/example/event_management/model/Users.java
> +    private RoleStatus roleStatus;
updated

2023-06-30 09:43 UTC, gajendraJangid421 commented on event_management/src/main/java/com/example/event_management/repository/UserEventRepository.java
> +    @Query("delete UserEvent userEvent where userEvent.eventId = :eventId")
updated

2023-06-30 09:44 UTC, gajendraJangid421 commented on event_management/src/main/java/com/example/event_management/repository/UserEventRepository.java
> +    @Query("delete UserEvent userEvent where userEvent.userId = :userId")
updated

2023-06-30 09:44 UTC, gajendraJangid421 commented on event_management/src/main/java/com/example/event_management/service/EventsService.java
> +        if(event.getTotalSeats()<1){
updated

2023-06-30 09:46 UTC, gajendraJangid421 commented on event_management/src/main/java/com/example/event_management/service/EventsService.java
> +        event.setId(UUID.randomUUID().toString());
updated

2023-06-30 09:49 UTC, gajendraJangid421 commented on event_management/src/main/java/com/example/event_management/service/UserEventService.java
> +    @Test
updated

2023-06-30 09:49 UTC, gajendraJangid421 commented on event_management/src/main/java/com/example/event_management/service/UserEventService.java
> +    @Test
updated

2023-06-30 09:51 UTC, gajendraJangid421 commented on event_management/src/main/java/com/example/event_management/service/UserEventService.java
> +                event.setSeatsLeft(event.getSeatsLeft()+1);
updated

2023-06-30 09:52 UTC, gajendraJangid421 commented on event_management/src/main/java/com/example/event_management/service/UserEventService.java
> +                event.setSeatsLeft(event.getSeatsLeft()-1);
updated

2023-06-30 13:32 UTC, gajendraJangid421 commented on event_management/src/main/java/com/example/event_management/service/EventsService.java
> +        if(events.getTotalSeats()<1){
updated

2023-07-02 12:22 UTC, gajendraJangid421 commented on event_management/src/main/java/com/example/event_management/service/UserEventService.java
> +            bookEvent.setBooked(!bookEvent.isBooked());
bookEvent.isBooked() is taken from mysql table and so it is changing its value after booking/not booking

2023-07-02 12:35 UTC, gajendraJangid421 commented on event_management/src/main/java/com/example/event_management/service/UserEventService.java
> +        }
updated

2023-07-03 10:27 UTC, gajendraJangid421 commented on event_management/src/main/java/com/example/event_management/service/SessionService.java
> +        sessionRepository.deleteById(sessionRepository.findByToken(token).getId());
updated

2023-07-03 10:47 UTC, gajendraJangid421 commented on event_management/src/main/java/com/example/event_management/controller/LoginController.java
> +    public void logOut(@PathVariable String id){
Kept as it is for Frontend
Will be updating by connecting to Rahul

2023-07-03 12:27 UTC, sagarzond commented
Looks good.

2023-07-03 14:18 UTC, AtulxD123 approved these changes

2023-07-03 14:31 UTC, merged